config/routes.rb
Rails.application.routes.draw do

  get 'infos' => 'infos#index', as: 'infos_index'

  get 'infos/:info_id' => 'infos#show', as: 'infos_show'

  get 'dashboards' => 'dashboards#show', as: 'dashboard'

  get 'static_pages/about'
  get 'static_pages/home'
  get 'static_pages/help'

  resources :states, only: [:index]
  resources :users, only: [:index, :show, :new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :companies, only: [:index]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get '/states/:state_id/stations' => 'stations#stateindex', as: 'station_index_state'
  get '/states/:state_id/rosens' => 'rosens#stateindex', as: 'rosen_index_state'

  get '/companies/categories/:category_id' => 'companies#show', as: 'companies_show'
  get '/companies/:company_id/stations' => 'stations#companyindex', as: 'station_index_company'
  get '/companies/:company_id/rosens' => 'rosens#companyindex', as: 'rosen_index_company'

  get '/stations/:station_id' => 'stations#show', as: 'station_detail'
  get '/stations/:station_id/edit' => 'user_station_statuses#edit', as: 'station_edit'
  patch '/stations/:station_id' => 'user_station_statuses#update', as: 'user_station_status'
  put '/stations/:station_id' => 'user_station_statuses#update'

  get '/rosens/:rosen_id' => 'rosens#show', as: 'rosen_detail'
  get '/rosens/:rosen_id/stations' => 'stations#rosenindex', as: 'station_index_rosen'

  get '/rosens/:rosen_id/edit' => 'user_section_statuses#edit', as: 'section_edit'
  patch '/rosens/:rosen_id' => 'user_section_statuses#update', as: 'user_section_status'
  put '/rosens/:rosen_id' => 'user_section_statuses#update'


  root 'dashboards#show'
end

app/models/station.rb
class Station < ActiveRecord::Base
  # 従属関係
  has_many :user_station_statuses
  belongs_to :state
  belongs_to :company

  scope :company_is, -> (company_id) { where("stations.company_id = ? and stations.delete_flag = ?", company_id, 0) }
  scope :state_is, -> (state_id) { where("stations.state_id = ? and stations.delete_flag = ?", state_id, 0) }
  scope :not_abolish, -> { where("stations.abolished_flag = ?", 0) }
  scope :abolish, -> { where("stations.abolished_flag = ?", 1) }
  scope :station_user_is, -> (user_id) { where("user_station_statuses.user_id = ?", user_id) }
  scope :visit_true, -> { where("user_station_statuses.visit_chk = ? and user_station_statuses.delete_flag = ?", 1, 0) }
  scope :not_delete, -> { where("stations.delete_flag = ?", 0) }

  enum abolished_flag: {not_abolished: 0, abolished: 1}
  enum delete_flag: {not_delete: 0, deleted: 1}
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def companyindex
    @Company = Company.find(params[:company_id])
    @Stations = Station.eager_load(:state, :user_station_statuses).company_is(params[:company_id]).station_user_is(current_user).not_delete.order(:name_ruby)
    @StationCount = Station.company_is(params[:company_id]).not_abolish.not_delete.count
    @VisitedCount = Station.eager_load(:state, :user_station_statuses).company_is(params[:company_id]).visit_true.station_user_is(current_user).not_abolish.not_delete.count
    @VisitedAboCount = Station.eager_load(:state, :user_station_statuses).company_is(params[:company_id]).visit_true.station_user_is(current_user).abolish.not_delete.count
  end

  def stateindex
    @State = State.find(params[:state_id])
    @Stations = Station.eager_load(:company, :state, :user_station_statuses).state_is(params[:state_id]).station_user_is(current_user).not_delete.order('companies.category_id asc, companies.company_sub_id asc, name_ruby asc')
    @StationCount = Station.state_is(params[:state_id]).not_abolish.not_delete.count
    @VisitedCount = Station.eager_load(:state, :user_station_statuses).state_is(params[:state_id]).visit_true.station_user_is(current_user).not_abolish.not_delete.count
    @VisitedAboCount = Station.eager_load(:state, :user_station_statuses).state_is(params[:state_id]).visit_true.station_user_is(current_user).abolish.not_delete.count
  end

  def rosenindex
    @Rosen = Rosen.find(params[:rosen_id])
    @Sections = Section.eager_load(:start_station, :end_station).rosen_is(params[:rosen_id]).not_abolish.not_delete.order("section_sub_id ASC")
    @SectionsLast = Section.eager_load(:start_station, :end_station).rosen_is(params[:rosen_id]).not_abolish.not_delete.order("section_sub_id DESC").limit(1)
  end

  def show
    @Station = Station.eager_load(:state, :company).find(params[:station_id])
    @StatusSearch = UserStationStatus.user_is(current_user).station_is(params[:station_id]).not_delete
    @StatusSearch.each do |s|
      $id = s.id
    end
    @Status = UserStationStatus.find($id)
    @Rosens = Section.eager_load(:rosen, :start_station, :end_station).where("sections.start_id = ? or sections.end_id = ?", params[:station_id], params[:station_id]
).not_abolish.not_delete.group(:rosen_id)

    @arr = Array.new()

    @Rosens.each do |r|

      $prev_station_id = 0
      $next_station_id = 0

      $rosen_id = r.rosen_id
      $rosen_name = r.rosen.name
      $rosen_start_station_name = r.rosen.start_station.name
      $rosen_end_station_name = r.rosen.end_station.name

      @PrevStation = Section.eager_load(:start_station, :end_station).where("sections.end_id = ? and sections.rosen_id = ?", params[:station_id], r.rosen_id).not_abolish.not_delete

      if (@PrevStation.nil?) 
        $prev_station_name.nil
        $prev_station_id.nil
      end     
      @PrevStation.each do |p|
        $prev_station_name = p.start_station.name
        $prev_station_id = p.start_station.id
      end
      @NextStation = Section.eager_load(:start_station, :end_station).where("sections.start_id = ? and sections.rosen_id = ?", params[:station_id], r.rosen_id).not_abolish.not_delete

      @NextStation.each do |n|
        $next_station_name = n.end_station.name
        $next_station_id = n.end_station.id
      end  
      @arr.push [[$rosen_id, $rosen_name, $rosen_start_station_name, $rosen_end_station_name, $prev_station_name, $prev_station_id, $next_station_name, $next_station_id]]
    end

  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/companyindex.html.erb
<% provide(:title, @Company.name + ' 駅一覧') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @Company.name + ' 路線一覧', rosen_index_company_path(@Company) %></li>
    <li><%= link_to @Company.name + ' 駅一覧', station_index_company_path(@Company) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @Company.name %> 駅一覧</h1>
</header>
<article>
  <section class="summary">
    <table border="1">
      <col span="3" width="100" />
      <tbody>
        <tr>
          <th>総営業駅数</th>
          <th>訪問駅数</th>
          <th>訪問率</th>
        </tr>
        <tr>
          <td class="kilo"><%= @StationCount %></td>
          <td class="kilo"><%= @VisitedCount %></td>
    <% if @StationCount == 0 %>
          <td class="kilo">-.-%</td>
    <% else %>
          <td class="kilo"><%= number_with_precision((@VisitedCount.to_f / @StationCount.to_f) * 100, :precision => 3) %>%</td>
    <% end %>
        </tr>
      </tbody>
    </table>
  </section>
  <table border="1">
    <col span="1" width="250" />
    <col span="1" width="300" />
    <col span="1" width="80" />
    <col span="1" width="100" />
    <col span="1" width="90" />
    <tbody>
      <tr>
        <th>駅名</th>
        <th>ふりがな</th>
        <th>都道府県</th>
        <th>訪問日</th>
        <th>訪問チェック</th>
      </tr>
    <% @Stations.each do |s| %>
        <% if s.abolished_flag? %>
      <tr class="abo">
        <% else %>
      <tr>
        <% end %>
        <td><%= link_to s.name, station_detail_path(s) %></td>
        <td><%= s.name_ruby %></td>
        <td><%= s.state.name %></td>
        <% s.user_station_statuses.each do |u| %>
        <td class="date"><%= u.visit_day %></td>
        <td class="chk"><% if u.visit_chk? %>●<% end %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</article>

app/views/stations/index.html.erb
<% provide(:title, @Company.name + ' 駅一覧') %>
<header>
  <h1 id="show"><%= @Company.name %> 駅一覧</h1>
</header>
<article>
  <section class="summary">
    <table border="1">
      <col span="3" width="80" />
      <tbody>
        <tr>
          <th>総営業駅数</th>
          <th>訪問駅数</th>
          <th>訪問率</th>
        </tr>
        <tr>
          <td class="kilo"><%= @StationCount %></td>
          <td class="kilo"><%= @VisitedCount %></td>
          <td class="kilo"><%= number_with_precision((@VisitedCount / @StationCount) * 100, :precision => 3) %>%</td>
        </tr>
      </tbody>
    </table>
  </section>
  <table border="1">
    <col span="1" width="200" />
    <col span="1" width="250" />
    <col span="3" width="75" />
    <tbody>
      <tr>
        <th>駅名</th>
        <th>ふりがな</th>
        <th>都道府県</th>
        <th>訪問日</th>
        <th>訪問チェック</th>
      </tr>
    <% @Stations.each do |s| %>
      <tr>
        <td><%= link_to s.name, station_detail_path(s) %></td>
        <td><%= s.name_ruby %></td>
        <td><%= s.state.name %></td>
        <% s.user_station_statuses.each do |u| %>
        <td class="date"><%= u.visit_day %></td>
        <td class="chk"><% if u.visit_chk? %>●<% end %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</article>

app/views/stations/rosenindex.html.erb
<% provide(:title, @Rosen.name + ' ' + @Rosen.start_station.name + '～' + @Rosen.end_station.name + ' 駅一覧') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @Rosen.company.name + ' 路線一覧', rosen_index_company_path(@Rosen.company_id) %></li>
    <li><%= link_to @Rosen.company.name + ' 駅一覧', station_index_company_path(@Rosen.company_id) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @Rosen.name %> （<%= @Rosen.start_station.name %>～<%= @Rosen.end_station.name %>） 駅一覧</h1>
</header>
<article>
<% if @Rosen.abolished_flag? %>
  <div id="announce">
    <p id="caution">路線廃止されているため、現存する駅はありません。</p>
  </div>
<% else %>
  <div id="announce">
    <p>※廃止された駅は表示されません。</p>
  </div>
  <table border="1">
    <col span="1" width="250" />
    <col span="1" width="300" />
    <col span="1" width="80" />
<!--    <col span="1" width="100" />
    <col span="1" width="90" />-->
    <tbody>
      <tr>
        <th>駅名</th>
        <th>ふりがな</th>
        <th>都道府県</th>
      </tr>
    <% @Sections.each do |s| %>
      <tr>
        <td><%= link_to s.start_station.name, station_detail_path(s.start_station.id) %></td>
        <td><%= s.start_station.name_ruby %></td>
        <td><%= s.start_station.state.name %></td>
      </tr>
    <% end %>
    <% @SectionsLast.each do |l| %>
      <tr>
        <td><%= link_to l.end_station.name, station_detail_path(l.end_station.id) %></td>
        <td><%= l.end_station.name_ruby %></td>
        <td><%= l.end_station.state.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
</article>

app/views/stations/show.html.erb
<% provide(:title, @Station.company.name + ' ' + @Station.name + '駅 詳細') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @Station.company.name + ' 路線一覧', rosen_index_company_path(@Station.company_id) %></li>
    <li><%= link_to @Station.company.name + ' 駅一覧', station_index_company_path(@Station.company_id) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @Station.company.name %> <%= @Station.name %>駅 詳細</h1>
</header>
<article>
<% if flash[:notice] %>
  <div id="sub">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>
  <div class="links">
    <ul>
      <li><%= link_to "訪問記録の編集", station_edit_path(@Station) %></li>
    </ul>
  </div>
<% if @Station.abolished_flag? %>
  <p id="abo_warn">この駅は廃止されています。</p>
<% end %>
  <dl id="station_summary">
    <dt>駅名 （ふりがな）<dt>
    <dd><%= @Station.name %> （<%= @Station.name_ruby %>）</dd>
    <dt>都道府県<dt>
    <dd><%= @Station.state.name %></dd>
    <dt>会社名<dt>
    <dd><%= @Station.company.name %></dd>
<% if !@Station.abolished_flag? %>
    <dt>接続路線</dt>
    <dd>
      <table border="1">
        <col span="1" width="200" />
        <col span="1" width="300" />
        <col span="1" width="200" />
        <tbody>
    <% @arr.each do |a| %>
    <% a.each do |a2| %>
          <tr>
            <td class="prev_station">&lt;<% if a2[5] != 0 %> <%= link_to a2[4], station_detail_path(a2[5]) %><% end %></td>
            <td class="rosen_name"><%= link_to a2[1] + " (" + a2[2] + "～" + a2[3] + ")", rosen_detail_path(a2[0]) %></td>
            <td class="next_station"><% if a2[7] != 0 %><%= link_to a2[6], station_detail_path(a2[7]) %> <% end %>&gt;</td>
          </tr>
    <% end %>
    <% end %>
        </tbody>
      </table>
    </dd>
<% end %>
    <dt>訪問記録</dt>
    <dd>
      <table border="1">
        <col span="1" width="100" />
        <col span="1" width="90" />
        <tbody>
          <tr>
            <th>訪問日</th>
            <th>訪問チェック</th>
          </tr>
          <tr>
            <td class="date"><%= @Status.visit_day %></td>
            <td class="chk"><% if @Status.visit_chk? %>訪問済み<% else %>未訪問<% end %></td>
          </tr>
        </tbody>
      </table>
    </dd>
  </dl>
  <div class="links">
    <ul>
      <li><%= link_to "訪問記録の編集", station_edit_path(@Station) %></li>
    </ul>
  </div>
</article>

app/views/stations/stateindex.html.erb
<% provide(:title, @State.name + ' 駅一覧') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @State.name + ' 駅間詳細', rosen_index_state_path(@State) %></li>
    <li><%= link_to @State.name + ' 駅一覧', station_index_state_path(@State) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @State.name %> 駅一覧</h1>
</header>
<article>
  <section class="summary">
    <table border="1">
      <col span="3" width="100" />
      <tbody>
        <tr>
          <th>総営業駅数</th>
          <th>訪問駅数</th>
          <th>訪問率</th>
        </tr>
        <tr>
          <td class="kilo"><%= @StationCount %></td>
          <td class="kilo"><%= @VisitedCount %></td>
    <% if @StationCount == 0 %>
          <td class="kilo">-.-%</td>
    <% else %>
          <td class="kilo"><%= number_with_precision((@VisitedCount.to_f / @StationCount.to_f) * 100, :precision => 3) %>%</td>
    <% end %>
        </tr>
      </tbody>
    </table>
  </section>
  <table border="1">
    <col span="1" width="200" />
    <col span="1" width="250" />
    <col span="1" width="300" />
    <col span="1" width="100" />
    <col span="1" width="90" />
    <tbody>
      <tr>
        <th>会社名</th>
        <th>駅名</th>
        <th>ふりがな</th>
        <th>訪問日</th>
        <th>訪問チェック</th>
      </tr>
    <% @Stations.each do |s| %>
        <% if s.abolished_flag? %>
      <tr class="abo">
        <% else %>
      <tr>
        <% end %>
        <td><%= s.company.name %></td>
        <td><%= link_to s.name, station_detail_path(s) %></td>
        <td><%= s.name_ruby %></td>
        <% s.user_station_statuses.each do |u| %>
        <td class="date"><%= u.visit_day %></td>
        <td class="chk"><% if u.visit_chk? %>●<% end %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</article>