config/routes.rb
Rails.application.routes.draw do

  get 'infos' => 'infos#index', as: 'infos_index'

  get 'infos/:info_id' => 'infos#show', as: 'infos_show'

  get 'dashboards' => 'dashboards#show', as: 'dashboard'

  get 'static_pages/about'
  get 'static_pages/home'
  get 'static_pages/help'

  resources :states, only: [:index]
  resources :users, only: [:index, :show, :new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :companies, only: [:index]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get '/states/:state_id/stations' => 'stations#stateindex', as: 'station_index_state'
  get '/states/:state_id/rosens' => 'rosens#stateindex', as: 'rosen_index_state'

  get '/companies/categories/:category_id' => 'companies#show', as: 'companies_show'
  get '/companies/:company_id/stations' => 'stations#companyindex', as: 'station_index_company'
  get '/companies/:company_id/rosens' => 'rosens#companyindex', as: 'rosen_index_company'

  get '/stations/:station_id' => 'stations#show', as: 'station_detail'
  get '/stations/:station_id/edit' => 'user_station_statuses#edit', as: 'station_edit'
  patch '/stations/:station_id' => 'user_station_statuses#update', as: 'user_station_status'
  put '/stations/:station_id' => 'user_station_statuses#update'

  get '/rosens/:rosen_id' => 'rosens#show', as: 'rosen_detail'
  get '/rosens/:rosen_id/stations' => 'stations#rosenindex', as: 'station_index_rosen'

  get '/rosens/:rosen_id/edit' => 'user_section_statuses#edit', as: 'section_edit'
  patch '/rosens/:rosen_id' => 'user_section_statuses#update', as: 'user_section_status'
  put '/rosens/:rosen_id' => 'user_section_statuses#update'


  root 'dashboards#show'
end

app/models/rosen.rb
class Rosen < ActiveRecord::Base
  # 従属関係
  has_many :sections
  has_many :user_rosen_statuses
  belongs_to :company
  belongs_to :start_station, class_name: "Station", foreign_key: "start_id"
  belongs_to :end_station, class_name: "Station", foreign_key: "end_id"

  scope :company_is, -> (company_id) { where("rosens.company_id = ? and rosens.delete_flag = ?", company_id, 0) }
  scope :rosen_is, -> (rosen_id) { where(["sections.rosen_id = ? and sections.delete_flag = ?", rosen_id, 0]) }
  scope :rosen_user_is, -> (user_id) { where("user_rosen_statuses.user_id = ? and user_rosen_statuses.delete_flag = ?", user_id, 0) }
  scope :section_user_is, -> (user_id) { where("user_section_statuses.user_id = ? and user_section_statuses.delete_flag = ?", user_id, 0) }
  scope :not_delete, -> { where("rosens.delete_flag = ?", 0) }

  enum abolished_flag: {not_abolished: 0, abolished: 1}
  enum delete_flag: {not_delete: 0, deleted: 1}
end

app/controllers/rosens_controller.rb
class RosensController < ApplicationController
  def companyindex
    @Company = Company.find(params[:company_id])
    @Rosens = Rosen.eager_load(:start_station, :end_station, :user_rosen_statuses).company_is(params[:company_id]).rosen_user_is(current_user).not_delete.order(:rosen_sub_id)
    @Rosen_sum = Rosen.eager_load(:start_station, :end_station).company_is(params[:company_id]).not_delete.sum(:kilo)
#    @Rosen_sum = Rosen.eager_load(:start_station, :end_station, :user_rosen_statuses).company_is(params[:company_id]).rosen_user_is(current_user).not_delete.sum(:kilo)
    @Ride_sum = Rosen.eager_load(:start_station, :end_station, :user_rosen_statuses).company_is(params[:company_id]).rosen_user_is(current_user).not_delete.sum(:ride_kilo_sum)
    @Ride_abo_sum = Rosen.eager_load(:start_station, :end_station, :user_rosen_statuses).company_is(params[:company_id]).rosen_user_is(current_user).not_delete.sum(:ride_abo_kilo_sum)
  end

  def stateindex
    @State = State.find(params[:state_id])
    @Sections = Section.eager_load(:rosen, :start_station, :end_station, :user_section_statuses).state_is(params[:state_id]).section_user_is(current_user).order("rosen_id, section_sub_id ASC")
  end

  def show
    @Rosen = Rosen.eager_load(:company).find(params[:rosen_id])
    @Sections = Section.eager_load(:user_section_statuses).rosen_is(params[:rosen_id]).section_user_is(current_user).not_delete.order("section_sub_id ASC")
    @Section_sum = Section.eager_load(:user_section_statuses).rosen_is(params[:rosen_id]).ride_true.section_user_is(current_user).not_delete.sum(:kilo)
  end
end

app/helpers/rosens_helper.rb
module RosensHelper
end

app/views/rosens/companyindex.html.erb
<% provide(:title, @Company.name + ' 路線一覧') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @Company.name + ' 路線一覧', rosen_index_company_path(@Company) %></li>
    <li><%= link_to @Company.name + ' 駅一覧', station_index_company_path(@Company) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @Company.name %> 路線一覧</h1>
</header>
<article>
  <table border="1">
    <col span="1" width="200" />
    <col span="2" width="250" />
    <col span="2" width="80" />
    <col span="1" width="90" />
    <col span="1" width="80" />
    <tbody>
      <tr>
        <th rowspan="2">路線名</th>
        <th rowspan="2">開始駅</th>
        <th rowspan="2">終了駅</th>
        <th colspan="3">現存区間</th>
        <th>廃止区間</th>
      </tr>
      <tr>
        <th>営業キロ</th>
        <th>乗車キロ</th>
        <th>乗車率</th>
        <th>乗車キロ</th>
      </tr>
    <% @Rosens.each do |r| %>
        <% if r.abolished_flag? %>
      <tr class="abo">
        <% else %>
      <tr>
        <% end %>
        <td><%= link_to r.name, rosen_detail_path(r) %></td>
        <td><%= r.start_station.name %></td>
        <td><%= r.end_station.name %></td>
        <td class="kilo"><%= r.kilo %></td>
        <% r.user_rosen_statuses.each do |u| %>
        <td class="kilo"><%= u.ride_kilo_sum %></td>
    <% if r.kilo == 0 %>
        <td class="kilo">-.-%</td>
    <% else %>
        <td class="kilo"><%= number_with_precision((u.ride_kilo_sum / r.kilo) * 100, :precision => 3) %>%</td>
    <% end %>
        <td class="kilo"><%= u.ride_abo_kilo_sum %></td>
        <% end %>
      </tr>
    <% end %>
      <tr>
        <td colspan="3" class="foot">合計</td>
        <td class="kilo"><%= @Rosen_sum %></td>
        <td class="kilo"><%= @Ride_sum %></td>
    <% if @Rosen_sum == 0 %>
        <td class="kilo">-.-%</td>
    <% else %>
        <td class="kilo"><%= number_with_precision((@Ride_sum / @Rosen_sum) * 100, :precision => 3) %>%</td>
    <% end %>
        <td class="kilo"><%= @Ride_abo_sum %></td>
      </tr>
    </tbody>
  </table>
</article>

app/views/rosens/index.html.erb
<% provide(:title, @Company.name + ' 路線一覧') %>
<header>
  <h1 id="show"><%= @Company.name %> 路線一覧</h1>
</header>
<article>
  <table border="1">
    <col span="1" width="35" />
    <col span="1" width="150" />
    <col span="2" width="200" />
    <tbody>
      <tr>
        <th rowspan="2">ID</th>
        <th rowspan="2">路線名</th>
        <th rowspan="2">開始駅</th>
        <th rowspan="2">終了駅</th>
        <th colspan="3">現存区間</th>
        <th>廃止区間</th>
      </tr>
      <tr>
        <th>営業キロ</th>
        <th>乗車キロ</th>
        <th>乗車率</th>
        <th>乗車キロ</th>
      </tr>
    <% @Rosens.each do |r| %>
      <tr>
        <td><%= r.id %></td>
        <td><%= link_to r.name, rosen_detail_path(r) %></td>
        <td><%= r.start_station.name %></td>
        <td><%= r.end_station.name %></td>
        <td class="kilo"><%= r.kilo %></td>
        <% r.user_rosen_statuses.each do |u| %>
        <td class="kilo"><%= u.ride_kilo_sum %></td>
        <td class="kilo"><%= number_with_precision((u.ride_kilo_sum / r.kilo) * 100, :precision => 3) %>%</td>
        <td class="kilo"><%= u.ride_abo_kilo_sum %></td>
        <% end %>
      </tr>
    <% end %>
      <tr>
        <td colspan="4" class="foot">合計</td>
        <td class="kilo"><%= @Rosen_sum %></td>
        <td class="kilo"><%= @Ride_sum %></td>
        <td class="kilo"><%= number_with_precision((@Ride_sum / @Rosen_sum) * 100, :precision => 3) %>%</td>
        <td class="kilo"><%= @Ride_abo_sum %></td>
      </tr>
    </tbody>
  </table>
</article>

app/views/rosens/show.html.erb
<% provide(:title, @Rosen.name + ' ' + @Rosen.start_station.name + '～' + @Rosen.end_station.name + ' 駅間詳細') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @Rosen.company.name + ' 路線一覧', rosen_index_company_path(@Rosen.company_id) %></li>
    <li><%= link_to @Rosen.company.name + ' 駅一覧', station_index_company_path(@Rosen.company_id) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @Rosen.name %> （<%= @Rosen.start_station.name %>～<%= @Rosen.end_station.name %>） 駅間詳細</h1>
</header>
<article>
<% if flash[:notice] %>
  <div id="sub">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>
  <div class="links">
    <ul>
      <li><%= link_to '乗車記録の編集', section_edit_path(@Rosen) %></li>
<% if !@Rosen.abolished_flag? %>
      <li><%= link_to @Rosen.name + ' 駅一覧', station_index_rosen_path(@Rosen) %></li>
<% end %>
    </ul>
  </div>
  <table border="1">
    <col span="2" width="250" />
    <col span="1" width="80" />
    <col span="1" width="100" />
    <col span="1" width="90" />
    <tbody>
      <tr>
        <th>開始駅</th>
        <th>終了駅</th>
        <th>営業キロ</th>
        <th>乗車日</th>
        <th>乗車チェック</th>
      </tr>
    <% @Sections.each do |s| %>
        <% if s.abolished_flag? %>
      <tr class="abo">
        <% else %>
      <tr>
        <% end %>
        <td><%= link_to s.start_station.name, station_detail_path(s.start_station.id) %></td>
        <td><%= link_to s.end_station.name, station_detail_path(s.end_station.id) %></td>
        <td class="kilo"><%= s.kilo %></td>
        <% s.user_section_statuses.each do |u| %>
        <td class="date"><%= u.ride_day %></td>
        <td class="chk"><% if u.ride_chk? %>●<%  end %></td>
        <% end %>
      </tr>
    <% end %>
      <tr>
        <td colspan="2" class="foot">合計</td>
        <td class="kilo"><%= @Rosen.kilo %></td>
        <td class="foot">乗車キロ</td>
        <td class="kilo"><%= @Section_sum %></td>
      </tr>
    </tbody>
  </table>
  <div class="links">  
    <ul>
      <li><%= link_to '乗車記録の編集', section_edit_path(@Rosen) %></li>
<% if !@Rosen.abolished_flag? %>
      <li><%= link_to @Rosen.name + ' 駅一覧', station_index_rosen_path(@Rosen) %></li>
<% end %>
    </ul>
  </div>
</article>

app/views/rosens/stateindex.html.erb
<% provide(:title, @State.name + ' ' + ' 駅間詳細') %>
<nav>
  <ul>
<%= render partial: 'nav' %>
    <li><%= link_to @State.name + ' 駅間詳細', rosen_index_state_path(@State) %></li>
    <li><%= link_to @State.name + ' 駅一覧', station_index_state_path(@State) %></li>
  </ul>
</nav>
<header>
  <h1 id="show"><%= @State.name %> 駅間詳細</h1>
</header>
<article>
  <div id="announce">
    <p>※この画面では編集が出来ません。編集を行う場合は、該当の路線名を選択してください。</p>
  </div>
  <table border="1">
    <col span="2" width="200" />
    <col span="2" width="250" />
    <col span="1" width="80" />
    <col span="1" width="100" />
    <col span="1" width="90" />
    <tbody>
      <tr>
        <th>会社名</th>
        <th>路線名</th>
        <th>開始駅</th>
        <th>終了駅</th>
        <th>営業キロ</th>
        <th>乗車日</th>
        <th>乗車チェック</th>
      </tr>
    <% @Sections.each do |s| %>
        <% if s.abolished_flag? %>
      <tr class="abo">
        <% else %>
      <tr>
        <% end %>
        <td><%= s.company.name %></td>
        <td><%= link_to s.rosen.name, rosen_detail_path(s.rosen_id) %></td>
        <td><%= link_to s.start_station.name, station_detail_path(s.start_station.id) %></td>
        <td><%= link_to s.end_station.name, station_detail_path(s.end_station.id) %></td>
        <td class="kilo"><%= s.kilo %></td>
        <% s.user_section_statuses.each do |u| %>
        <td class="date"><%= u.ride_day %></td>
        <td class="chk"><% if u.ride_chk? %>●<%  end %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</article>